config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :projects do
    resources :feedbacks
  end
  
  resources :feedbacks do
    resources :projects
    get 'feedbacks'
  end
  
  resources :contacts, only: [:new, :create]

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, :validate => true
    attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message, :validate => true
    attribute :nickname, :captcha => true
    
    def headers
        {
        :subject => "Contact Form",
        :to => "support@myfirstlabs.com",
        :from => %("#{name}" <#{email}>)
        }
    end

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :project
  validates :commenter, length: { maximum: 31 }
  validates :title, presence: true, length: { maximum: 256 }
  validates :body, presence: true, length: { maximum: 65535 }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :feedbacks, dependent: :destroy
  validates :name, presence: true, length: { maximum: 32 }
  validates :description, presence: true, length: { maximum: 65535 }
end

app/models/user.rb
# Schema: User(name:string, password_digest:string)
class User < ActiveRecord::Base
  has_secure_password
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = 'Error sending message.'
            render 'new'
        end
    end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @feedback = @project.feedback.create(feedback_params)
    redirect_to project_path(@project)
  end
  
  private
    def feedback_params
      params.require(:feedback).permit(:commenter, :title, :body)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :logged_in_user
  
  def create
    @project = Project.find(params[:project_id])
    @feedback = @project.feedbacks.create(feedback_params)
    redirect_to project_path(@project)
  end
  
  def new
    @feedback = new
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def index
    @feedback = Feedback.all
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    redirect_to feedbacks_path
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end
  
  def update
    @feedback = Feedback.find(params[:id])
    if @feedback.update(feedback_params)
      redirect_to @feedback
    else
      render 'edit'
    end
  end

  private
  def feedback_params
    params.require(:feedback).permit(:commenter, :title, :body, :is_approved)
  end
  
  def logged_in_user
    unless current_user
    flash[:danger] = "Administrative function; Please log in"
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
  
  def new
     @projects = Project.new
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def create
    @projects = Project.new(project_params)
    
    if @projects.save
      redirect_to @projects
    else
      render 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    
    redirect_to projects_path
  end

private
  def project_params
    params.require(:project).permit(:name, :description, :image, :video)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:error] = "Invalid Login"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div id="container">
  <p>Your message has been sent!</p>
  <br><br><br>
  <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>
</div>

app/views/contacts/new.html.erb
<div id="container">
  <h2>Contact My First Labs!</h2>
  <%= form_for @contact do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, placeholder: "Name, Required" %>
    </p>
    
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email, required: true,  placeholder: "Email, Required" %>
    </p>
    
    <p>
      <%= f.label :message %><br>
      <%= f.text_area :message, required: true,  placeholder: "Message, Required" %>
    </p>
    
    <p style= "display: none;">
      <%= f.label :nickname %><br>
      <%= f.text_area :nickname %>
    </p>

    <p><%= f.submit "Send Message" %></p>
    
  <% end %>
  <br><br><br>
  <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>
</div>

app/views/contacts/show.html.erb
<div id="container">
  <p>Your message has been sent!</p>
  <br><br><br>
  <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>
</div>

app/views/feedbacks/edit.html.erb
<div id="container"> <!-- Feedback information -->
  <% if current_user %>
    <h2>Feedback Approval Form</h2>
  
    <br> <!-- Much needed whitespace -->
  
    <p>Name: <%= @feedback.commenter %></p>
    <h3>Subject: <%= @feedback.title %></h3>
    <p>Body: <%= @feedback.body %></p>
  
    <br><br><br> <!-- Much needed whitespace -->
  
    <%= form_for :feedback, url: feedback_path, method: :patch do |f| %>
      <br>
      <%= f.check_box :is_approved %>
      <%= f.label 'Allow this feedback to be visible under the relevant project' %>
      <br> <!-- Much needed whitespace -->
      <p><%= f.submit "Save Feedback Approval Settings" %></p>
    <% end %>
  
    <br><br><br> <!-- Much needed whitespace -->
  
    <%= link_to 'Back to Feedback List', feedbacks_path, :class=>"backward" %>
  <% else %>
    <h2>LOGIN TO VIEW CONTENT</h2>
  <% end %>
</div>

app/views/feedbacks/index.html.erb
<div id="container">
  <% if current_user %>
    <h2>Feedback Editor</h2>
  
    <table class="info">
      <tr>
        <th class="info-1">Project</th>
        <th class="info-2">Name</th>
        <th class="info-3">Subject</th>
        <th class="info-4">Visible</th>
        <th class="info-5">Link to Details</th>
      </tr>
      <!-- Below loop will show the all the feedback information and actions that can be taken -->
      <% @feedback.each do |feedback| %>
      <tr>
        <td class="info-1"><%= feedback.project.name %></td>
        <td class="info-2">
          <% if feedback.commenter == '' then %> <!-- Check if anonymous -->
            Anonymous
          <% else %> <!-- If not anonymous -->
            <%= feedback.commenter %>
          <% end %>        
        </td>
        <td class="info-3"><%= feedback.title %></td>
        <td class="info-4">
          <% if feedback.is_approved %>
            Yes
          <% else %>
            No
          <% end %>
        </td>
        <td class="info-5"><%= link_to "View/Edit Feedback", feedback_path(feedback), :class=>"forward" %></td>

      </tr>
      <% end %>
    </table>
  <% else %>
    <h2>LOGIN TO VIEW CONTENT</h2>
  <% end %>
</div>

app/views/feedbacks/show.html.erb
<div id="container"> <!-- Project information -->
  <% if current_user %>
    <h2>Subject: <%= @feedback.title %></h2>
    <p>Body <%= @feedback.body %></p>
    
    <br><br>
    
    Name: 
    <% if @feedback.commenter == '' then %> <!-- Check if anonymous -->
      Anonymous
    <% else %>
      <%= @feedback.commenter %>
    <% end %>
    
    <br><br>
    
    Visible:
    <% if @feedback.is_approved %>
      Yes
    <% else %>
      No
    <% end %>
    
    <br><br><br>
    
    <%= link_to 'Return to Feedbacks', feedbacks_path, :class=>"backward" %>
    
    <br><br><br>
    
    <%= link_to 'Change Feedback Settings', edit_feedback_path(@feedback), :class=>"edit" %>
    <%= link_to 'Remove Feedback', [@feedback.project, @feedback],
      method: :delete,
      data: { confirm: 'Are you sure?' },
      :class=>"delete"
    %>
  <% else %>
    <h2>LOGIN TO VIEW CONTENT</h2>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfirstlabs</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Almendra+Display" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav_wrapper">
      <ul>
        <% if current_user %>
          <li><%= link_to "Log Out", logout_path, id: "logout" %></li>
          <li><%= link_to 'Feedback', feedbacks_path %></li>
        <% else %>
          <li><%= link_to "Staff Login", login_path, id: "login" %></li>
        <% end %>
        <li><%= link_to 'Contact', 'contacts/new' %></li>
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Home', root_path %></li>
      </ul>
       <h1 align="left" >My First Labs</h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div id="container">
  <% if current_user %>
    <h2>Editing Project</h2>
    
    <!-- The following loop is just a form for input -->
    <%= form_for :project, url: project_path(@project), method: :patch do |f| %>
      <% if @project.errors.any? %> <!-- Check for form input errors -->
        <div>
          <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:<br>
          <% @project.errors.full_messages.each do |msg| %>
            <%= msg %><br>
          <% end %>
        </div>
      <% end %>
      <!-- Start of input form -->
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder: "Required" %>
      </p>
      <p>
        <%= f.label :image %><br>
        <%= f.text_field :image, placeholder: "Optional"  %>
      </p>
      <p>
        <%= f.label :video %><br>
        <%= f.text_field :video, placeholder: "Optional"  %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, placeholder: "Required" %>
      </p>
      <p><%= f.submit "Save Project Changes" %></p>
    <% end %>
    
    <br><br><br><!-- Much needed whitespace -->
    
    <%= link_to 'Back to Project', project_path(@project), :class=>"backward" %>
  <% else %>
    <h2>LOGIN TO VIEW CONTENT</h2>
  <% end %>
</div>

app/views/projects/index.html.erb
<div id="container">
  <h2>Available Project Kits</h2>
  <a href="https://www.tindie.com/stores/mscharlotte/" class="forward"> To order full parts kits online, click here. </a>
  <br><br>
  <!-- Start of staff only items -->
    <% if current_user %>
      <%= link_to 'New Project', new_project_path, :class=>"new" %>
    <% end %>
  <!-- End of staff only items -->

  <br><br> <!-- Much needed whitespace -->

  <!-- Below loop will show the name and tumbnail with a link to the projects -->
  <ul class="project_tile_holder">
  <% @projects.each do |project| %>
    <li class = "project_tile">
      <%= link_to project.name , project_path(project), :class=>"forward" %>
      <br><br>
      <% unless project.image == '' then %> <!-- Check if image is linked -->
        <img src= <%= project.image %> alt="imgur.com" style="width: 200px;">
      <% else %> <!-- If not picture is linked -->
        <br><br><br><br> <!-- Muched needed whitespace -->
        Image Pending!
        <br><br><br><br> <!-- Much needed whitespace -->
      <% end %>

      <br><br><br> 
    </li><!-- Whitespace to divide different projects better -->
  <% end %>
  </ul>
  <br><br><br>
</div>

app/views/projects/new.html.erb
<div id="container">
  <% if current_user %>
    <h2>New Project</h2>
  
    <!-- The following loop is just a form for input -->
    <%= form_for :project, url: projects_path do |f| %>
      <% if @projects.errors.any? %> <!-- Check for form input errors -->
        <div>
          <%= pluralize(@projects.errors.count, "error") %> prohibited this project from being saved:<br>
          <% @projects.errors.full_messages.each do |msg| %>
            <%= msg %><br>
          <% end %>
        </div>
      <% end %>
      <!-- Start of input form -->
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder: "Required" %>
      </p>
      <p>
        <%= f.label :image %><br>
        <%= f.text_field :image, placeholder: "Optional"  %>
      </p>
      <p>
        <%= f.label :video %><br>
        <%= f.text_field :video, placeholder: "Optional"  %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, placeholder: "Required" %>
      </p>
      <p><%= f.submit "Create Project Record" %></p>
    <% end %>
  
    <br><br><br><!-- Much needed whitespace -->
  
    <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>
  <% else %>
    <h2>LOGIN TO VIEW CONTENT</h2>
  <% end %>
</div>

app/views/projects/show.html.erb
<div id="container"> <!-- Project information -->
  <h2><%= @project.name %></h2>
  <p><%= @project.description %></p>
  <% unless @project.image == '' then %> <!-- Check if image is linked -->
    <img src= <%= @project.image %> alt="imgur.com" style="width: 500px;">
  <% else %> <!-- If not picture is linked -->
    <br><br><br><br> <!-- Muched needed whitespace -->
    Image Pending!
    <br><br><br><br> <!-- Much needed whitespace -->
  <% end %>
  <br>
  <% unless @project.video == '' then %> <!-- Check if video is linked -->
    <a class="forward" href=<%= @project.video %>> Instructionional Video</a>
  <% else %> <!-- If not video is linked -->
    Video Pending!
  <% end %>
  
  <!-- Start of staff only items -->
    <% if current_user %>
      <br><br><br> <!-- Need whitespace -->
      <%= link_to 'Edit Project', edit_project_path(@project), :class=>"edit" %>
      <%= link_to 'Remove Project', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, :class=>"delete" %><br>
    <% end %>
  <!-- End of staff only items -->
  
  <br><br><br> <!-- Need whitespace -->

  <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>

  <br><br><br> <!-- Need whitespace -->
  
  <h3>User Feedback</h3>
  <% count = 0 %> <!-- Counter variable to count approved feedbacks -->
  <!-- Below loop will show the the feedback on the project -->
  <% @project.feedbacks.each do |feedback| %>
    <% if feedback.is_approved == true then %>
      <% unless feedback.commenter == '' then %> <!-- If feedback is not anonymous -->
        <p>Name: <%= feedback.commenter  %></p>
      <% else %> <!-- If anonymous -->
        <p>Name: Anonymous</p>
      <% end %>
      <h4>Subject: <%= feedback.title %></h4>
      <p>Body: <%= feedback.body %></p>
      <br> <!-- Need whitespace -->
      <% count = count + 1 %>
    <% end %>
  <% end %>
  <% if count == 0 then %> <!-- If no approved feedbacks -->
    <p> No Feedback Reported Yet! </p>
  <% end %>

  <br><br>

  <h4>Give us some feedback:</h4> <!-- Form for feeback input -->
  <%= form_for([@project, @project.feedbacks.build]) do |f| %>
    <p>
      <%= f.label 'Name' %><br>
      <%= f.text_field :commenter, placeholder: "Optional" %>
    </p>
    <p>
      <%= f.label 'Subject' %><br>
      <%= f.text_field :title, placeholder: "Required" %>
    </p>
    <p>
      <%= f.label 'Body' %><br>
      <%= f.text_area :body, placeholder: "Required" %>
      </p>
    <p><%= f.submit "Submit Feedback" %></p>
  <% end %>
  
  <br><br><br>

  <%= link_to 'Back to Projects', projects_path, :class=>"backward" %>
</div>

app/views/welcome/index.html.erb
<div id="container">
  <h1> My First Labs </h1>
  <p style="font-style:italic; font-size:18px">Build your own early electronic devices at home, in school, or any educational setting!</p>
  
  <div id="slider">
  <img class="slides" id="teslacoil" src="http://i.imgur.com/V4NAVpl.jpg" >
  <img class="slides" id="brusslessmotor" src="http://i.imgur.com/c67BCpL.jpg" >
  <img class="slides" id="hotwireknife" src="http://i.imgur.com/ftiPUP8.jpg" >
  <img class="slides" id="bugbot" src="http://i.imgur.com/4h7lDre.jpg" >
  <img class="slides" id="rocketglider" src="http://i.imgur.com/IjsETwY.jpg" >
  <img class="slides" id="helicopter" src="http://i.imgur.com/zl6F2rX.jpg" >
  
  <button class="button" onclick="plusDivs(-1)" id="b1">&#10094;</button>
  <button class="button" onclick="plusDivs(1)"id="b2">&#10095;</button>
  </div>
  <br><br><br>

</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function gotoDivs(n) {
	showDivs(slideIndex=n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("slides");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}

</script>